//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_1000(void);
int64_t function_1003(void);
int32_t function_1030(char * format, ...);
void function_1040(void);
int32_t function_1050(char * format, ...);
int32_t function_1060(char * s1, char * s2);
int32_t function_1070(char * s);
int64_t function_1083(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_10e0(void);
int64_t function_1123(void);
int64_t function_1170(void);
int64_t function_1173(void);
int64_t function_1179(int64_t * a1, int64_t a2, int64_t a3);
int64_t function_11c6(void);
int64_t function_13f3(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1463(void);
int64_t function_146b(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1170;
int64_t g2 = 0x1120;
int64_t g3; // 0x4081
int64_t g4 = 0; // rax
int32_t g5;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int64_t function_1000(void) {
    // 0x1000
    return g4;
}

// Address range: 0x1003 - 0x101b
int64_t function_1003(void) {
    // 0x1003
    int64_t result; // 0x101a
    if (*(int64_t *)0x3ff0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g5;
    } else {
        result = 0;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
void function_1040(void) {
    // 0x1040
    __stack_chk_fail();
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(char * format, ...) {
    // 0x1050
    return scanf(format);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * s1, char * s2) {
    // 0x1060
    return strcmp(s1, s2);
}

// Address range: 0x1070 - 0x1076
int32_t function_1070(char * s) {
    // 0x1070
    return puts(s);
}

// Address range: 0x1080 - 0x1081
int64_t entry_point(void) {
    // 0x1080
    int64_t result; // rax
    return result;
}

// Address range: 0x1083 - 0x10d9
int64_t function_1083(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x1083
    int64_t v1;
    __libc_start_main(0x11c6, (int32_t)a4, (char **)&v1, (void (*)())0x13f0, (void (*)())0x1460, (void (*)())a3);
    __asm_hlt();
    return 0x4088;
}

// Address range: 0x10e0 - 0x1119
int64_t function_10e0(void) {
    // 0x10e0
    return 0;
}

// Address range: 0x1123 - 0x1161
int64_t function_1123(void) {
    // 0x1123
    int64_t result; // rax
    if (*(char *)0x4081 != 0) {
        // 0x1160
        return result;
    }
    if (*(int64_t *)0x3fd8 == 0) {
        // branch -> 0x1148
    } else {
        // 0x113b
        __cxa_finalize((int64_t *)*(int64_t *)0x4048);
        result = &g5;
    }
    // 0x1148
    *(char *)&g3 = 1;
    return result;
}

// Address range: 0x1170 - 0x1171
int64_t function_1170(void) {
    // 0x1170
    int64_t result; // rax
    return result;
}

// Address range: 0x1173 - 0x1179
int64_t function_1173(void) {
    // 0x1173
    return function_10e0();
}

// Address range: 0x1179 - 0x11c6
int64_t function_1179(int64_t * a1, int64_t a2, int64_t a3) {
    int64_t result = (int64_t)a1; // rdi
    uint32_t v1 = (int32_t)a2; // 0x1193
    if (v1 <= 0) {
        // 0x11c0
        return result;
    }
    int64_t v2 = 0;
    char * v3 = (char *)(v2 + result); // 0x11a5
    *v3 = (char)((int64_t)*v3 ^ a3);
    while ((int32_t)(v2 + 1) != v1) {
        // 0x1198
        v2++;
        v3 = (char *)(v2 + result);
        *v3 = (char)((int64_t)*v3 ^ a3);
    }
    // 0x11c0
    return result;
}

// Address range: 0x11c6 - 0x13ef
int64_t function_11c6(void) {
    int64_t v1 = __readfsqword(40); // 0x11d1
    int64_t v2 = 0x3534323160376761; // bp-424
    printf("Enter key: ");
    int64_t str; // bp-280
    scanf("%s", &str);
    int64_t str2 = function_1179(&v2, 32, 3); // 0x1397
    if (strcmp((char *)&str, (char *)str2) != 0) {
        // 0x13c8
        puts("try again!");
    } else {
        // 0x13ba
        puts("good job!");
    }
    // 0x13d4
    int64_t result; // 0x13ee
    if (v1 == __readfsqword(40)) {
        // 0x13d4
        result = 0;
    } else {
        // 0x13e8
        __stack_chk_fail();
        result = &g5;
    }
    // 0x13ed
    return result;
}

// Address range: 0x13f3 - 0x1455
int64_t function_13f3(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = function_1000(); // 0x141c
    if (((int64_t)&g2 - (int64_t)&g1) / 8 != 0) {
        int64_t v1 = 0; // 0x143d2
        while (v1 + 1 != ((int64_t)&g2 - (int64_t)&g1) / 8) {
            // 0x1430
            v1++;
        }
    }
    // 0x1446
    return result;
}

// Address range: 0x1463 - 0x1465
int64_t function_1463(void) {
    // 0x1463
    int64_t result; // rax
    return result;
}

// Address range: 0x146b - 0x1475
int64_t function_146b(void) {
    // 0x146b
    int64_t result; // rax
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void __stack_chk_fail(void);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int scanf(const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.2.1)
// Detected language: C++
// Detected functions: 18
// Decompilation date: 2019-07-15 07:10:51
