//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_7d8(void);
int32_t function_800(char * s);
void function_808(void);
int32_t function_810(char * command);
int32_t function_818(int32_t seconds);
void (*function_820(int32_t sig, void (*handler)(int32_t)))(int32_t);
int32_t function_828(int32_t flag, char * format, ...);
int32_t function_830(struct _IO_FILE * stream, char * buf, int32_t modes, int32_t n);
int32_t function_838(char * format, ...);
void function_840(int32_t status);
void function_848(int64_t * d);
int64_t function_850(void);
int64_t function_930(void);
int64_t function_970(int64_t * a1);
int64_t function_9c0(void);
int64_t function_a00(void);
int64_t function_a3e(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_a90(int64_t a1, int64_t a2, int64_t a3);
int64_t function_b00(void);
int64_t function_b04(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 2560;
int64_t g2 = 2496;
int64_t g3 = 0;
struct _IO_FILE * g4 = NULL;
int64_t g5 = 0;
struct _IO_FILE * g6 = NULL;
char g7 = 0;
int32_t g8;

// ------------------------ Functions -------------------------

// Address range: 0x7d8 - 0x7ef
int64_t function_7d8(void) {
    // 0x7d8
    int64_t result;
    if (*(int64_t *)0x200fc0 != 0) {
        // 0x7e8
        __gmon_start__();
        result = &g8;
    } else {
        result = 0;
    }
    // 0x7ea
    return result;
}

// Address range: 0x800 - 0x806
int32_t function_800(char * s) {
    // 0x800
    return puts(s);
}

// Address range: 0x808 - 0x80e
void function_808(void) {
    // 0x808
    __stack_chk_fail();
}

// Address range: 0x810 - 0x816
int32_t function_810(char * command) {
    // 0x810
    return system(command);
}

// Address range: 0x818 - 0x81e
int32_t function_818(int32_t seconds) {
    // 0x818
    return alarm(seconds);
}

// Address range: 0x820 - 0x826
void (*function_820(int32_t sig, void (*handler)(int32_t)))(int32_t) {
    // 0x820
    return signal(sig, handler);
}

// Address range: 0x828 - 0x82e
int32_t function_828(int32_t flag, char * format, ...) {
    // 0x828
    return __printf_chk(flag, format);
}

// Address range: 0x830 - 0x836
int32_t function_830(struct _IO_FILE * stream, char * buf, int32_t modes, int32_t n) {
    // 0x830
    return setvbuf(stream, buf, modes, n);
}

// Address range: 0x838 - 0x83e
int32_t function_838(char * format, ...) {
    // 0x838
    return scanf(format);
}

// Address range: 0x840 - 0x846
void function_840(int32_t status) {
    // 0x840
    exit(status);
}

// Address range: 0x848 - 0x84e
void function_848(int64_t * d) {
    // 0x848
    __cxa_finalize(d);
}

// Address range: 0x850 - 0x8f6
int64_t function_850(void) {
    int64_t v1 = __readfsqword(40); // bp+854
    int64_t v2; // rcx
    int64_t v3; // rdi
    int64_t v4; // rdx
    int64_t v5; // rsi
    function_a3e(v3, v5, v4, v2);
    int32_t v6 = 0; // bp-24
    int32_t v7 = 0; // bp-20
    __printf_chk(1, "1337 input: ");
    scanf("%u %u", &v6, &v7);
    if (v6 > 0x1336) {
        goto lab_0x8b7;
    } else {
        if (v7 > 0x1336) {
            goto lab_0x8b7;
        } else {
            // 0x8c5
            if (v6 - v7 == 0x1337) {
                // 0x8ce
                system("cat /flag");
            }
            goto lab_0x8da;
        }
    }
  lab_0x8b7:
    // 0x8b7
    puts("Sowwy");
    goto lab_0x8da;
  lab_0x8da:;
    // 0x8da
    int64_t result;
    if ((__readfsqword(40) ^ v1) == 0) {
        // 0x8da
        result = 0;
    } else {
        // 0x8ec
        __stack_chk_fail();
        result = &g8;
    }
    // 0x8f1
    return result;
}

// Address range: 0x900 - 0x92b
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x900
    int64_t v1;
    __libc_start_main(2128, (int32_t)a4, (char **)&v1, (void (*)())2704, (void (*)())2816, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x930 - 0x962
int64_t function_930(void) {
    if ((uint64_t)((int64_t)&g5 - (int64_t)&g4) < 14 || (int64_t)&g5 - (int64_t)&g4 == 14) {
        // 0x960
        return (int64_t)&g5 - (int64_t)&g4;
    }
    // 0x94b
    if (*(int64_t *)0x200f88 == 0) {
        // 0x960
        return 0;
    }
    // 0x957
    return _ITM_deregisterTMCloneTable((int64_t *)&g4);
}

// Address range: 0x970 - 0x9b2
int64_t function_970(int64_t * a1) {
    // 0x9b0
    return 0;
}

// Address range: 0x9c0 - 0x9f2
int64_t function_9c0(void) {
    // 0x9c0
    if (g7 != 0) {
        // 0x9f0
        int64_t result; // rax
        return result;
    }
    if (*(int64_t *)0x200ff8 != 0) {
        // 0x9d7
        __cxa_finalize((int64_t *)*(int64_t *)0x201008);
    }
    // 0x9e3
    g7 = 1;
    // 0x9f0
    return function_930();
}

// Address range: 0xa00 - 0xa30
int64_t function_a00(void) {
    // 0xa00
    if (g3 == 0 || *(int64_t *)0x200fd8 == 0) {
        // 0xa0d
        return function_970(&g3);
    }
    _Jv_RegisterClasses(&g3);
    return function_970(&g3);
}

// Address range: 0xa3e - 0xa88
int64_t function_a3e(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0xa3e
    setvbuf(g4, NULL, 2, 0);
    setvbuf(g6, NULL, 2, 0);
    signal(SIGALARM, 2608);
    return alarm(60);
}

// Address range: 0xa90 - 0xaf5
int64_t function_a90(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = function_7d8();
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 != 0) {
        int64_t v1 = 0; // 0xadd2
        while (v1 != ((int64_t)&g2 - (int64_t)&g1 >> 3) - 1) {
            // 0xad0
            v1++;
        }
    }
    // 0xae6
    return result;
}

// Address range: 0xb00 - 0xb02
int64_t function_b00(void) {
    // 0xb00
    int64_t result; // rax
    return result;
}

// Address range: 0xb04 - 0xb0d
int64_t function_b04(void) {
    // 0xb04
    int64_t result; // rax
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// int __printf_chk(int flag, const char * restrict format, ...);
// void __stack_chk_fail(void);
// int64_t _ITM_deregisterTMCloneTable(int64_t * a1);
// int64_t _Jv_RegisterClasses(int64_t * a1);
// unsigned int alarm(unsigned int seconds);
// void exit(int status);
// int puts(const char * s);
// int scanf(const char * restrict format, ...);
// int setvbuf(FILE * restrict stream, char * restrict buf, int modes, size_t n);
// __sighandler_t signal(int sig, __sighandler_t handler);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.0)
// Detected functions: 21
// Decompilation date: 2019-07-13 22:19:49
