//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t vuln(void);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL;
int32_t g2;

// ------------------------ Functions -------------------------

// Address range: 0x80485ab - 0x8048643
int32_t vuln(void) {
    int32_t v1 = __readgsdword(20); // 0x80485b5
    int32_t buf; // bp-144
    __asm_rep_stosd_memset((char *)&buf, 0, 32);
    system("echo input your message:");
    read(0, &buf, 127);
    printf((char *)&buf);
    puts("\n");
    puts("Thanks for sending the message!");
    int32_t result; // 0x8048642
    if (__readgsdword(20) != v1) {
        // 0x8048639
        __stack_chk_fail();
        result = &g2;
    } else {
        result = 0;
    }
    // 0x804863e
    return result;
}

// Address range: 0x8048643 - 0x8048696
int main(int argc, char ** argv) {
    // 0x8048643
    setvbuf(g1, NULL, 2, 0);
    int32_t v1 = getegid(); // 0x8048668
    setresgid(v1, v1, v1);
    vuln();
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// __gid_t getegid(void);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// ssize_t read(int fd, void * buf, size_t nbytes);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);
// int setvbuf(FILE * restrict stream, char * restrict buf, int modes, size_t n);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 2
// Decompilation date: 2019-07-17 12:01:53
