//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t setup(void);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL;
struct _IO_FILE * g2 = NULL;
int64_t g3 = 0; // rbp
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x4007c4 - 0x400822
int64_t setup(void) {
    // 0x4007c4
    setvbuf(g1, NULL, 2, 0);
    setvbuf(g2, NULL, 2, 0);
    signal(SIGALARM, 0x4007b6);
    return alarm(60);
}

// Address range: 0x400835 - 0x40090c
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x40083d
    setup();
    int64_t v2 = 0; // bp-128
    int64_t v3 = 0; // bp-120
    int64_t v4 = 0; // bp-112
    int64_t v5; // bp-104
    __asm_rep_stosq_memset((char *)&v5, 0, 10);
    printf("Input: ");
    while (scanf("%ld %ld %ld", &v2, &v3, &v4) == 3) {
        // 0x4008b7
        *(int64_t *)(8 * v4 - 96 + g3) = v3 + v2;
        printf("Result: %ld", (int32_t)*(int64_t *)(8 * v4 - 96 + g3));
        v2 = 0;
        v3 = 0;
        v4 = 0;
        __asm_rep_stosq_memset((char *)&v5, 0, 10);
        printf("Input: ");
    }
    // 0x4008cd
    int64_t result; // 0x40090b
    if (v1 == __readfsqword(40)) {
        // 0x4008cd
        result = 0;
    } else {
        // 0x400905
        __stack_chk_fail();
        result = &g4;
    }
    // 0x40090a
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// unsigned int alarm(unsigned int seconds);
// int printf(const char * restrict format, ...);
// int scanf(const char * restrict format, ...);
// int setvbuf(FILE * restrict stream, char * restrict buf, int modes, size_t n);
// __sighandler_t signal(int sig, __sighandler_t handler);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.0)
// Detected functions: 2
// Decompilation date: 2019-07-14 02:00:42
